### ISSUE TITLE
Report: Project plan

### ISSUE THREAD

**Issue by OscarFredriksson** [OscarFredriksson/sims-2021#19]
- [ ] What features we will have
- [ ] What features we will not have
- [ ] Key work packages
